services:
  hotel:
    image: hotel
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DISPLAY=$DISPLAY # Pass the host display
    depends_on:
      - db
    entrypoint: ["./entrypoint.sh"]
  # "db" service
  db:
    # Name of the image to be pulled from Docker Hub.
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: p
      MYSQL_DATABASE: hotel # Automatically create the 'HC' database
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Database_Dump.sql:/docker-entrypoint-initdb.d/db.sql # Load db.sql on initialization
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
